<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Distribusi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('MTransaksi');
        $this->load->library('form_validation');
    }

    public function index()
    {

        $data = array(
            'transaksi_data' => $this->db->query("SELECT *,transaksi.id as id,barang.id as id_barang FROM transaksi INNER JOIN barang ON transaksi.kode_barang = barang.kode WHERE status = 'dikirim'")->result()
        );
        $data['page'] = 'distribusi/distribusi_list';
        $this->load->view('template', $data);
    }

}

/* End of file Transaksi.php */
/* Location: ./application/controllers/Transaksi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-29 15:33:49 */
/* http://harviacode.com */