<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MUser extends CI_Model
{

    public $table = 'user';

    function __construct()
    {
        parent::__construct();
    }

    public function CheckUser($u, $p)
    {
        $query = $this->db->get_where(
            $this->table,
            array(
                'username' => $u,
                'password' => $p
            )
        );
        if ($query->num_rows() > 0) {
            return true;
        } else {
            return false;
        }
    }
    function get_by_username($username)
    {
        $this->db->where('username', $username);
        return $this->db->get($this->table)->row();
    }
}

/* End of file MBarang.php */
/* Location: ./application/models/MBarang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-29 05:23:40 */
/* http://harviacode.com */